In [1]:
import tensorflow as tf


In [2]:
print(tf.__version__)

2.3.1


In [22]:
! nvidia-smi

Sat Jan 22 02:42:02 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 497.29       Driver Version: 497.29       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8     3W /  N/A |   3300MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [24]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU')]

In [26]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

## tf.constant()

In [18]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [19]:
scalar.ndim

0

In [20]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [21]:
vector.ndim

1

In [22]:
matrix= tf.constant([[1,2],
                    [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [23]:
matrix.ndim

2

In [24]:
tensor = tf.constant([[[1,1,1],
                        [2,2,2]],
                        [[3,3,3],
                        [4,4,4]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])>

In [25]:
tensor.ndim

3

## tf.variable()

In [26]:
change=tf.Variable([1,2])
change

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [27]:
change[0].assign(3)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 2])>

In [28]:
change

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 2])>

In [29]:
change.assign("new") #should be of same data type

TypeError: Cannot convert 'new' to EagerTensor of dtype int32

In [ ]:
change.assign([4,5,6]) #should be of same dimension

ValueError: Shapes (2,) and (3,) are incompatible

## tf.random.Generator

In [30]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [31]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [32]:
random_1==random_2 #if dim is same, it will give element wise equality

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [33]:
random_3=tf.random.Generator.from_seed(42) #loacl seed to genrator
random_3 = random_3.normal(shape=(3,3))
random_3

random_3, random_3==random_2 #if any parameter differs, it will return overall FALSE

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=bool, numpy=False>)

In [34]:
tf.random.set_seed(42) #global seed for generator
random_4 = tf.random.normal(shape=(3,2))
random_4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519],
       [-2.3880599, -1.0392479]], dtype=float32)>

## tf.random.shuffle()

In [35]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [36]:
tf.random.shuffle(random_2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193765, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [37]:
tf.random.shuffle(random_2, seed = 42) #local seed mentioned

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [38]:
tf.random.set_seed(42)
tf.random.shuffle(random_2,seed = 42) # Global and Local seed mentioned

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

## Other ways

In [39]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [40]:
tf.zeros([2,4], dtype= "int32")

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [41]:
import numpy as np

array_1 = np.arange(1,25)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [42]:
tensor_1 = tf.constant(array_1, shape=(3,8), dtype="float16")
tensor_1

<tf.Tensor: shape=(3, 8), dtype=float16, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.]], dtype=float16)>

## Tensor Attributes

In [43]:
tensor_2 = tf.zeros(shape=(2,3,4,5))
tensor_2

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
tensor_2.shape

TensorShape([2, 3, 4, 5])

In [47]:
tensor_2.ndim

4

In [48]:
tensor_2.dtype

tf.float32

In [49]:
tf.size(tensor_2)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [50]:
tf.size(tensor_2).numpy()

120

## Slicing and Indexing

In [55]:
tensor_2[:2,:3,:2,:2] #first two element of each dimension

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [57]:
tensor_2[1,1,1], tensor_2[1,1,1,:] #first element form each dimention except from the last one [SCALAR]

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>)

In [58]:
tensor_2[:1,:1,:1], tensor_2[:1,:1,:1,:] #first element form each dimention except from the last one [VECTOR]

(<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>)

In [61]:
tensor_2[1,1,:,1].shape

TensorShape([4])

In [64]:
tensor_2[:1,:1,:,:1].shape

TensorShape([1, 1, 4, 1])

## Expanding dimension

In [65]:
ten_3 = tf.random.normal([2,2])

In [66]:
ten_3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519]], dtype=float32)>

In [79]:
ten_3[:,:,tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[ 0.3274685],
        [-0.8426258]],

       [[ 0.3194337],
        [-1.4075519]]], dtype=float32)>

In [81]:
tf.expand_dims(ten_3,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[ 0.3274685],
        [-0.8426258]],

       [[ 0.3194337],
        [-1.4075519]]], dtype=float32)>

#### Numpy

In [69]:
arr_2 = np.random.normal(size=(2,2)) 
arr_2

array([[0.1355362 , 0.73121468],
       [0.03442766, 0.12216119]])

In [77]:
arr_2[:,:,None], arr_2[:,:,None].shape #adding new dimension in numpy

(array([[[0.1355362 ],
         [0.73121468]],
 
        [[0.03442766],
         [0.12216119]]]),
 (2, 2, 1))

In [76]:
arr_2[:,None], arr_2[:,None].shape

(array([[[0.1355362 , 0.73121468]],
 
        [[0.03442766, 0.12216119]]]),
 (2, 1, 2))

In [82]:
np.expand_dims(arr_2,axis=1)

array([[[0.1355362 , 0.73121468]],

       [[0.03442766, 0.12216119]]])

## Tensor Operations

In [6]:
tensor_5 = tf.random.Generator.from_seed(35)
tensor_5=tf.random.normal(shape=(2,2))
tensor_5

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0927877 ,  0.67106295],
       [ 1.2981657 ,  0.834623  ]], dtype=float32)>

In [10]:
# tensor also sopports element wwise operation like Numpy

tensor_5+10, tensor_5-2, tensor_5+tensor_5

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 7.9072123, 10.671062 ],
        [11.298165 , 10.834623 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-4.0927877, -1.328937 ],
        [-0.7018343, -1.165377 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-4.1855755,  1.3421259],
        [ 2.5963314,  1.669246 ]], dtype=float32)>)

In [13]:
tf.add(tensor_5,10), tf.subtract(tensor_5,2), tf.multiply(tensor_5,2), #tf functions use gpu to execute 

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 7.9072123, 10.671062 ],
        [11.298165 , 10.834623 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-4.0927877, -1.328937 ],
        [-0.7018343, -1.165377 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-4.1855755,  1.3421259],
        [ 2.5963314,  1.669246 ]], dtype=float32)>)

In [14]:
tf.divide(tensor_5,2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.0463939 ,  0.33553147],
       [ 0.64908284,  0.4173115 ]], dtype=float32)>

In [15]:
tf.linalg.matmul(tensor_5,tensor_5)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5.2509117, -0.8443078],
       [-1.6333063,  1.5677464]], dtype=float32)>

In [16]:
tf.matmul(tensor_5,tensor_5)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5.2509117, -0.8443078],
       [-1.6333063,  1.5677464]], dtype=float32)>

In [17]:
tensor_5 @ tensor_5 #matrix multiplication 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5.2509117, -0.8443078],
       [-1.6333063,  1.5677464]], dtype=float32)>

In [20]:
tensor_5, tf.transpose(tensor_5)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-2.0927877 ,  0.67106295],
        [ 1.2981657 ,  0.834623  ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-2.0927877 ,  1.2981657 ],
        [ 0.67106295,  0.834623  ]], dtype=float32)>)

In [18]:
tensor_7= tf.random.Generator.from_seed(34)
tensor_7 = tf.random.normal(shape=(4,4))
tensor_7

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.01564945, -1.5829111 , -0.0869351 , -1.3381404 ],
       [-1.1953901 ,  1.8962443 ,  0.0070015 , -1.758392  ],
       [-1.6345816 , -0.1082655 , -0.97525865, -0.3962402 ],
       [-0.98479694,  0.11316141,  0.40221134, -0.6846833 ]],
      dtype=float32)>

In [4]:
tf.reshape(tensor_7, [2,8]) # axis = 0, there is no option to change it.

<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[-0.858272  , -0.21825325,  0.10915674, -0.21480684,  1.3454244 ,
        -0.21979016, -0.03776454,  0.05440208],
       [ 1.9126039 , -1.0161828 ,  0.8645902 ,  0.99913365,  0.11887364,
        -1.856555  , -0.35332143,  0.37929723]], dtype=float32)>

In [10]:
tensor_7.shape

TensorShape([4, 4])

In [11]:
tf.tensordot(tensor_7,tensor_7,axes=1)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.6262263 ,  0.5231681 ,  0.08482777,  0.2000758 ],
       [-1.5162127 , -0.30796033,  0.10329014, -0.31806067],
       [-1.2363422 , -2.9276133 ,  0.64165026,  0.77668697],
       [-3.2305555 ,  0.03696094, -0.35640427, -0.33568424]],
      dtype=float32)>

In [12]:
tf.tensordot(tensor_7,tensor_7,0)

<tf.Tensor: shape=(4, 4, 4, 4), dtype=float32, numpy=
array([[[[ 7.36630857e-01,  1.87320665e-01, -9.36861709e-02,
           1.84362695e-01],
         [-1.15474010e+00,  1.88639745e-01,  3.24122496e-02,
          -4.66917790e-02],
         [-1.64153433e+00,  8.72161269e-01, -7.42053568e-01,
          -8.57528448e-01],
         [-1.02025919e-01,  1.59342921e+00,  3.03245902e-01,
          -3.25540185e-01]],

        [[ 1.87320665e-01,  4.76344824e-02, -2.38238126e-02,
           4.68822904e-02],
         [-2.93643266e-01,  4.79699187e-02,  8.24223459e-03,
          -1.18734296e-02],
         [-4.17432010e-01,  2.21785203e-01, -1.88699633e-01,
          -2.18064174e-01],
         [-2.59445589e-02,  4.05199170e-01,  7.71135539e-02,
          -8.27828571e-02]],

        [[-9.36861709e-02, -2.38238126e-02,  1.19151929e-02,
          -2.34476142e-02],
         [ 1.46862134e-01, -2.39915755e-02, -4.12225397e-03,
           5.93835302e-03],
         [ 2.08773598e-01, -1.10923193e-01,  9.43758

> Not really understand how it is working. 
>>  (only undestanding) index value of the given axes must be same

In [19]:
tf.math.log(tensor_7)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-4.1573195 ,         nan,         nan,         nan],
       [        nan,  0.63987523, -4.9616313 ,         nan],
       [        nan,         nan,         nan,         nan],
       [        nan, -2.17894   , -0.9107776 ,         nan]],
      dtype=float32)>

In [20]:
tf.math.sqrt(tensor_7) # tf.sqrt( ) also works

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.12509775,        nan,        nan,        nan],
       [       nan, 1.3770418 , 0.08367495,        nan],
       [       nan,        nan,        nan,        nan],
       [       nan, 0.33639473, 0.63420135,        nan]], dtype=float32)>

In [21]:
tf.math.square(tensor_7) #tf.square() also works

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[2.4490527e-04, 2.5056076e+00, 7.5577120e-03, 1.7906196e+00],
       [1.4289575e+00, 3.5957425e+00, 4.9020979e-05, 3.0919423e+00],
       [2.6718569e+00, 1.1721418e-02, 9.5112944e-01, 1.5700629e-01],
       [9.6982503e-01, 1.2805506e-02, 1.6177396e-01, 4.6879125e-01]],
      dtype=float32)>

## tf.cast()

In [83]:
tensor_4 = tf.random.normal(shape=(3,2))
tensor_4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.08422458, -0.86090374],
       [ 0.37812304, -0.00519627],
       [-0.49453196,  0.6178192 ]], dtype=float32)>

In [85]:
tf.cast(tensor_4, dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 0.0842  , -0.861   ],
       [ 0.3782  , -0.005196],
       [-0.4946  ,  0.6177  ]], dtype=float16)>

## Aggregation

In [88]:
ten_3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519]], dtype=float32)>

In [89]:
tf.abs(ten_3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.3274685, 0.8426258],
       [0.3194337, 1.4075519]], dtype=float32)>

In [92]:
tf.reduce_max(ten_3)

<tf.Tensor: shape=(), dtype=float32, numpy=0.3274685>

In [93]:
tf.reduce_min(ten_3)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.4075519>

In [94]:
tf.reduce_mean(ten_3)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.40081888>

In [95]:
tf.reduce_sum(ten_3)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.6032755>

In [104]:
pip install tensorflow_probability==0.11.0

  Attempting uninstall: cloudpickle
    Found existing installation: cloudpickle 2.0.0
    Uninstalling cloudpickle-2.0.0:
      Successfully uninstalled cloudpickle-2.0.0
  Attempting uninstall: tensorflow-probability
    Found existing installation: tensorflow-probability 0.12.2
    Uninstalling tensorflow-probability-0.12.2:
      Successfully uninstalled tensorflow-probability-0.12.2
Note: you may need to restart the kernel to use updated packages.


#### Variance

In [105]:
import tensorflow_probability as tfp

In [109]:
ten_3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519]], dtype=float32)>

In [111]:
tfp.stats.variance(ten_3,sample_axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.34228015, 0.7456198 ], dtype=float32)>

In [112]:
tfp.stats.variance(ten_3,sample_axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.6139604e-05, 7.9785377e-02], dtype=float32)>

In [114]:
tfp.stats.variance(ten_3, sample_axis=None) # get cumulative variance

<tf.Tensor: shape=(), dtype=float32, numpy=0.5644677>

In [120]:
#ANOTHER WAY
tf.math.reduce_variance(ten_3), tf.math.reduce_variance(ten_3, axis=0)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.5644677>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.6139604e-05, 7.9785377e-02], dtype=float32)>)

#### Standard Deviantion

In [115]:
tf.math.reduce_std(ten_3, axis=None) #overall

<tf.Tensor: shape=(), dtype=float32, numpy=0.75131065>

In [121]:
tf.math.reduce_std(tf.cast(ten_3, dtype=tf.float16),axis=0) #axis wise

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([0.00403, 0.2822 ], dtype=float16)>

> Note: while finding variance and standard deviation, dtype must be float

## tf.argmin(), tf.argmax()

In [145]:
tensor_4.numpy()

array([[ 0.08422458, -0.86090374],
       [ 0.37812304, -0.00519627],
       [-0.49453196,  0.6178192 ]], dtype=float32)

In [140]:
tensor_4.shape

TensorShape([3, 2])

In [144]:
tf.argmax(tensor_4, axis=0) 
#shape of the resultant array would be shape of given tensor deleting the given index
#eg. shape of the tensor be (2,3,4,5), and asix =0, shape of the resultant array be (3,4,5)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 2], dtype=int64)>

In [131]:
tf.argmin(tensor_4, axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 0], dtype=int64)>

In [132]:
tf.argmin(tensor_4, axis=None) #resultant would be n dimensional array

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 0], dtype=int64)>

In [136]:
tf.argmin(tensor_4,axis=None).numpy()

array([2, 0], dtype=int64)

In [138]:
tensor_4[2,0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.49453196>

## tf.squeeze()

In [13]:
tensor_8 = tf.random.Generator.from_seed(23)
tensor_8 = tf.random.normal(shape=(2,4,1,6,))
tensor_8

<tf.Tensor: shape=(2, 4, 1, 6), dtype=float32, numpy=
array([[[[-0.6446809 ,  0.8159403 ,  0.11580312,  0.3281211 ,
          -0.947368  , -0.14559036]],

        [[ 1.1695122 ,  0.5414487 ,  1.00479   , -0.7541149 ,
           1.9501262 , -0.35160655]],

        [[ 0.38969547, -0.08306441, -0.09717955,  0.7107149 ,
           0.9336866 , -1.905859  ]],

        [[-0.01182606, -0.0552645 ,  0.84607995, -1.0036052 ,
          -3.5852373 , -0.73406476]]],


       [[[-1.2727537 ,  0.3228549 ,  1.3804178 ,  1.9109461 ,
          -0.56047565, -0.62826836]],

        [[-1.0099213 ,  1.2777008 , -1.1642952 ,  2.2482014 ,
          -0.7149551 ,  0.49648932]],

        [[-1.8474268 , -1.0165257 , -1.3275284 ,  2.1689703 ,
           1.2771971 , -0.779271  ]],

        [[ 0.49033746,  1.3874469 ,  0.37433827, -0.87655014,
          -0.21225712, -0.5279557 ]]]], dtype=float32)>

In [14]:
tf.squeeze(tensor_8), tf.squeeze(tensor_8).shape

(<tf.Tensor: shape=(2, 4, 6), dtype=float32, numpy=
 array([[[-0.6446809 ,  0.8159403 ,  0.11580312,  0.3281211 ,
          -0.947368  , -0.14559036],
         [ 1.1695122 ,  0.5414487 ,  1.00479   , -0.7541149 ,
           1.9501262 , -0.35160655],
         [ 0.38969547, -0.08306441, -0.09717955,  0.7107149 ,
           0.9336866 , -1.905859  ],
         [-0.01182606, -0.0552645 ,  0.84607995, -1.0036052 ,
          -3.5852373 , -0.73406476]],
 
        [[-1.2727537 ,  0.3228549 ,  1.3804178 ,  1.9109461 ,
          -0.56047565, -0.62826836],
         [-1.0099213 ,  1.2777008 , -1.1642952 ,  2.2482014 ,
          -0.7149551 ,  0.49648932],
         [-1.8474268 , -1.0165257 , -1.3275284 ,  2.1689703 ,
           1.2771971 , -0.779271  ],
         [ 0.49033746,  1.3874469 ,  0.37433827, -0.87655014,
          -0.21225712, -0.5279557 ]]], dtype=float32)>,
 TensorShape([2, 4, 6]))